name: Run Terraform Infra_DepoOrdering

on:
  workflow_dispatch:
    inputs:
      directory:
        description: 'Name of the working directory'
        required: true
        default: 'terraform/dev'
env:
  working-directory: '${{ github.event.inputs.directory }}'

jobs:
  check_s3_buckets:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: List S3 Buckets
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CLOUDIAN_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUDIAN_SECRET_KEY }}
        run: |
          aws s3 ls

  terraform_plan:
    runs-on: self-hosted
    needs: check_s3_buckets
    strategy:
      matrix:
        environment: ["perf"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Plan Infrastructure
        env:
          TF_VAR_refreshToken: ${{ secrets.TF_REFRESH_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.CLOUDIAN_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUDIAN_SECRET_KEY }}
        run: |
          cp ../../.github/workflows/plan.sh .
          ./plan.sh ${{ secrets.TF_REFRESH_TOKEN }}
        if: always()
        working-directory: ./ordering/${{matrix.environment}}
      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v2
        with:
          name: terraform-plan
          path: ./ordering/${{matrix.environment}}/tfplan
#
#  terraform_apply:
#    needs: terraform_plan
#    runs-on: self-hosted
#    strategy:
#      matrix:
#        environment: ["build-agents"]
#    environment: ${{matrix.environment}}
#    steps:
#      - name: Checkout Repository
#        uses: actions/checkout@v2
#      - name: Terraform Apply
#        env:
#          TF_VAR_refreshToken: ${{ secrets.TF_REFRESH_TOKEN }}
#          AWS_ACCESS_KEY_ID: ${{ secrets.CLOUDIAN_ACCESS_KEY }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUDIAN_SECRET_KEY }}
#        run: |
#          cp ../../.github/workflows/apply.sh .
#          ./apply.sh ${{ secrets.TF_REFRESH_TOKEN }}
#        working-directory: ./ordering/${{matrix.environment}}
